### ISSUE TITLE
'lein figwheel' fails to start using Clojure-1.8.0-beta1 

### ISSUE THREAD

**Issue by frankhale** [bhauman/devcards#56]
I tried using Clojure-1.8.0-beta1 in my devcards project.clj but when I run 'lein figwheel' it errors out with the following:

```
Exception in thread "main" java.lang.VerifyError: (class: cljs/util$last_modified, method: invokeStatic signature: (Ljava/lang/Object;)Ljava/l
ang/Object;) Can only throw Throwable objects, compiling:(util.cljc:142:1)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:463)
        at clojure.lang.Compiler.eval(Compiler.java:6918)
        at clojure.lang.Compiler.load(Compiler.java:7360)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5669.invoke(core.clj:5885)
        at clojure.core$load.invokeStatic(core.clj:5884)
        at clojure.core$load_one.invokeStatic(core.clj:5685)
        at clojure.core$load_one.invoke(core.clj)
        at clojure.core$load_lib$fn__5618.invoke(core.clj:5730)
        at clojure.core$load_lib.invokeStatic(core.clj:5729)
        at clojure.core$load_lib.doInvoke(core.clj)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:647)
        at clojure.core$load_libs.invokeStatic(core.clj:5767)
        at clojure.core$load_libs.doInvoke(core.clj)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:647)
        at clojure.core$require.invokeStatic(core.clj:5789)
        at clojure.core$require.doInvoke(core.clj)
        at clojure.lang.RestFn.invoke(RestFn.java:2088)
        at cljs.repl$eval15$loading__5561__auto____16.invoke(repl.cljc:9)
        at cljs.repl$eval15.invokeStatic(repl.cljc:9)
        at cljs.repl$eval15.invoke(repl.cljc)
        at clojure.lang.Compiler.eval(Compiler.java:6913)
        at clojure.lang.Compiler.eval(Compiler.java:6902)
        at clojure.lang.Compiler.load(Compiler.java:7360)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5669.invoke(core.clj:5885)
        at clojure.core$load.invokeStatic(core.clj:5884)
        at clojure.core$load_one.invokeStatic(core.clj:5685)
        at clojure.core$load_one.invoke(core.clj)
        at clojure.core$load_lib$fn__5618.invoke(core.clj:5730)
        at clojure.core$load_lib.invokeStatic(core.clj:5729)
        at clojure.core$load_lib.doInvoke(core.clj)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:647)
        at clojure.core$load_libs.invokeStatic(core.clj:5767)
        at clojure.core$load_libs.doInvoke(core.clj)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:647)
        at clojure.core$require.invokeStatic(core.clj:5789)
        at clojure.core$require.doInvoke(core.clj)
        at clojure.lang.RestFn.invoke(RestFn.java:3204)
        at figwheel_sidecar.repl$eval9$loading__5561__auto____10.invoke(repl.clj:1)
        at figwheel_sidecar.repl$eval9.invokeStatic(repl.clj:1)
        at figwheel_sidecar.repl$eval9.invoke(repl.clj)
        at clojure.lang.Compiler.eval(Compiler.java:6913)
        at clojure.lang.Compiler.eval(Compiler.java:6902)
        at clojure.lang.Compiler.load(Compiler.java:7360)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5669.invoke(core.clj:5885)
        at clojure.core$load.invokeStatic(core.clj:5884)
        at clojure.core$load_one.invokeStatic(core.clj:5685)
        at clojure.core$load_one.invoke(core.clj)
        at clojure.core$load_lib$fn__5618.invoke(core.clj:5730)
        at clojure.core$load_lib.invokeStatic(core.clj:5729)
        at clojure.core$load_lib.doInvoke(core.clj)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:647)
        at clojure.core$load_libs.invokeStatic(core.clj:5767)
        at clojure.core$load_libs.doInvoke(core.clj)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:647)
        at clojure.core$require.invokeStatic(core.clj:5789)
        at clojure.core$require.doInvoke(core.clj)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval5.invokeStatic(form-init179302172574647946.clj:1)
        at user$eval5.invoke(form-init179302172574647946.clj)
        at clojure.lang.Compiler.eval(Compiler.java:6913)
        at clojure.lang.Compiler.eval(Compiler.java:6902)
        at clojure.lang.Compiler.load(Compiler.java:7360)
        at clojure.lang.Compiler.loadFile(Compiler.java:7298)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.VerifyError: (class: cljs/util$last_modified, method: invokeStatic signature: (Ljava/lang/Object;)Ljava/lang/Object;) Can
 only throw Throwable objects
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at clojure.lang.Compiler$ObjExpr.eval(Compiler.java:4902)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:450)
        ... 93 more
Subprocess failed
```

**Comment by frankhale** [comment]
It may be an issue in figwheel rather than devcards.

**Comment by bhauman** [comment]
Is this a minimal devcards project?

**Comment by frankhale** [comment]
yes

**Comment by frankhale** [comment]
I've only got a few cards and I'm not doing any Clojure specific stuff. Switching back to 1.7.0 works.

**Comment by frankhale** [comment]
This can be reproduced by creating a new project using the devcards template then switch Clojure from 1.7.0 to 1.8.0-beta1.

**Comment by bhauman** [comment]
Is it only devcards or is it figwheel?

**Comment by frankhale** [comment]
Actually this is a figwheel issue. Doing the same process as described above but using the figwheel template results in the same issue.

**Comment by bhauman** [comment]
I haven't been able to reproduce this with 1.8.0-RC2 and cljs 1.7.170.  I'm thinking it is either fixed or a local issue or a Clojure windows issue.

**Comment by frankhale** [comment]
Yep this works well with 1.8.0-RC2 and CLJS 1.7.170. Thanks!
